env:
  browser: true
  commonjs: true
  es6: true
globals:
  describe: true
  it: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: module
plugins:
  - mocha
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  space-infix-ops: error
  mocha/handle-done-callback:
    - error
  mocha/no-exclusive-tests:
    - error
  mocha/no-global-tests:
    - error
  mocha/no-identical-title:
    - warn
  mocha/no-nested-tests:
    - error
  mocha/no-pending-tests:
    - warn
  mocha/no-sibling-hooks:
    - warn
  mocha/no-top-level-hooks:
    - warn
